name: Build latest release

on:
  push:
    tags:
      - '*'

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Tag Build
      uses: exportarts/jenkins-build-tag-action@1.0.0
      with:
        jenkins_host: https://jenkins.exportarts.io
        jenkins_basic_auth_token: ${{secrets.JENKINS_BASIC_AUTH_TOKEN}}
        jenkins_job: fsp-demo-app
